//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC__EmpApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EMPLOYEEEntities : DbContext
    {
        public EMPLOYEEEntities()
            : base("name=EMPLOYEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual int CreateEmployee(Nullable<int> eMPLOYEE_ID, string eMPLOYEE_NAME, string dEPARTMENT)
        {
            var eMPLOYEE_IDParameter = eMPLOYEE_ID.HasValue ?
                new ObjectParameter("EMPLOYEE_ID", eMPLOYEE_ID) :
                new ObjectParameter("EMPLOYEE_ID", typeof(int));
    
            var eMPLOYEE_NAMEParameter = eMPLOYEE_NAME != null ?
                new ObjectParameter("EMPLOYEE_NAME", eMPLOYEE_NAME) :
                new ObjectParameter("EMPLOYEE_NAME", typeof(string));
    
            var dEPARTMENTParameter = dEPARTMENT != null ?
                new ObjectParameter("DEPARTMENT", dEPARTMENT) :
                new ObjectParameter("DEPARTMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateEmployee", eMPLOYEE_IDParameter, eMPLOYEE_NAMEParameter, dEPARTMENTParameter);
        }
    
        public virtual int DeleteEmployee(Nullable<int> eMPLOYEE_ID)
        {
            var eMPLOYEE_IDParameter = eMPLOYEE_ID.HasValue ?
                new ObjectParameter("EMPLOYEE_ID", eMPLOYEE_ID) :
                new ObjectParameter("EMPLOYEE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteEmployee", eMPLOYEE_IDParameter);
        }
    
        public virtual ObjectResult<DisplayEmployee_Result> DisplayEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DisplayEmployee_Result>("DisplayEmployee");
        }
    
        public virtual int UpdateEmployee(string eMPLOYEE_NAME, string dEPARTMENT)
        {
            var eMPLOYEE_NAMEParameter = eMPLOYEE_NAME != null ?
                new ObjectParameter("EMPLOYEE_NAME", eMPLOYEE_NAME) :
                new ObjectParameter("EMPLOYEE_NAME", typeof(string));
    
            var dEPARTMENTParameter = dEPARTMENT != null ?
                new ObjectParameter("DEPARTMENT", dEPARTMENT) :
                new ObjectParameter("DEPARTMENT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateEmployee", eMPLOYEE_NAMEParameter, dEPARTMENTParameter);
        }
    }
}
